server:
  port: 8087

spring:
  application:
    name: cijian-search
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
      config:
        import-check:
          enabled: false
        server-addr: ${NACOS_ADDR:localhost:8848}
        file-extension: yml
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  elasticsearch:
    uris: ${ES_URIS:http://localhost:9200}

rocketmq:
  name-server: ${ROCKETMQ_NAMESRV:localhost:9876}
  producer:
    group: cijian-search-producer

logging:
  level:
    com.cijian.search: info
  file:
    name: logs/${spring.application.name}.log
spring.cloud.nacos.discovery.ip: 127.0.0.1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
